CREATE TABLE  IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    release_date DATE,
    duration INTEGER
);

CREATE TABLE IF NOT EXISTS user_friends (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, friend_id),

    CONSTRAINT fk_user_friends_user
      FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT fk_user_friends_friend
      FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_user_like (
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, film_id),

    CONSTRAINT fk_film_like_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT fk_film_like_film
        FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ratingMPA (
    mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS film_ratingMPA (
    film_id BIGINT NOT NULL PRIMARY KEY,
    mpa_id BIGINT NOT NULL,


    CONSTRAINT fk_film
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT mpa_id_const
    FOREIGN KEY (mpa_id) REFERENCES ratingMPA(mpa_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_film_id
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT fk_genre_id
    FOREIGN KEY (genre_id) REFERENCES genre(genre_id) ON DELETE CASCADE
);


INSERT INTO ratingMPA (rating)
SELECT *
FROM (
         SELECT 'G'
         UNION ALL SELECT 'PG'
         UNION ALL SELECT 'PG-13'
         UNION ALL SELECT 'R'
         UNION ALL SELECT 'NC-17'
     ) t(rating)
WHERE NOT EXISTS (SELECT 1 FROM ratingMPA);

INSERT INTO genre (name)
SELECT *
FROM (
         SELECT 'Комедия'
         UNION ALL SELECT 'Драма'
         UNION ALL SELECT 'Мультфильм'
         UNION ALL SELECT 'Триллер'
         UNION ALL SELECT 'Документальный'
         UNION ALL SELECT 'Боевик'
     ) t(name)
WHERE NOT EXISTS (SELECT 1 FROM genre);